output_dir: ~/HYPER/output

dataset:
  class: {{ dataset }}
  root: ~/HYPER/kg-datasets/
  version: {{ version }}

model:
  class: HYPER
  relation_model:
    class: RelHCNet
    input_dim: 64
    hidden_dims: [64, 64, 64, 64, 64, 64]
    aggregate_func:  sum
    short_cut: yes
    use_triton: yes
  entity_model:
    class: EntityHCNet
    input_dim: 64
    hidden_dims: [64, 64, 64, 64, 64, 64]
    aggregate_func: sum
    short_cut: yes
    use_triton: yes
    remove_easy_edges: yes

optimizer:
  class: AdamW
  lr: 3.0e-4

task:
  name: InductiveInference
  num_negative: 32
  num_corrupt_positions: 1
  num_eval_positions: 1
  negative_sampling: strict_typed
  typed_eval: yes
  node_specific_typed_evaluation: no
  adversarial_temperature: 1
  metric: [mr, mrr, hits@1, hits@3, hits@10]

train:
  gpus: {{ gpus }}
  batch_size: 8
  num_epoch: {{ epochs }}
  # Do evaluation after every epoch, test purposes only, to have a denser curve.
  eval_interval: 1
  # Log interval is set to 10, meaning log every 10 batches, test purposes
  log_interval: 10
  batch_per_epoch: {{ bpe }}
  num_eval_edges: 1000
  log_train_metrics: false

checkpoint: {{ ckpt }}
